version: "3.8"
services:
  mios:
    image: "msrm/mios:release"
    environment:
      - output=debug
      - database_port=27005
    network_mode: "host"
    cap_add:
      - SYS_NICE
    depends_on:
      - "ros"
      - "mongo"
  ros:
    image: "ros:melodic-ros-core"
    network_mode: "host"
    command: roscore
  mongo:
    image: "mongo:4.0.20-xenial"
    ports:
      - "27005:27017"
