services:
  mios:
    image: "mirmi/mios:FR3"
    restart: always
    environment:
      - verbosity=debug
      - robot_ip=192.168.3.100
      - ROBOT_USER=MBZUAI
      - ROBOT_PASSWORD=mbzuai123
      - database_name=miosL
      - database_port=27017
      - robot_config=0
      - desk=true
      - websocket_port=12000
      - rpc_port=12001
      - udp_port=12002
    network_mode: "host"
    cap_add:
      - SYS_NICE
    depends_on:
      - "mongo"
  mongo:
    image: "mongo:7.0.14"
    ports:
      - "27017:27017"
    volumes:
      - ./localFolder:/data/db
    command: mongod --quiet --logpath /dev/null 

  mios_mls:
    image: "mirmi/mios_mls:latest"
    ports:
      - "8000:8000"
      - "8001:8001"
    network_mode: "host"
    cap_add:
      - SYS_NICE



