# Get mios version from utils/include/utils/version.hpp and put it in MIOS_VERSION
function(get_mios_version)
    file(READ "${CMAKE_CURRENT_LIST_DIR}/utils/include/utils/version.hpp" file_contents)
    string(REGEX MATCH "MIOS_VER_MAJOR ([0-9]+)" _ "${file_contents}")
    if(NOT CMAKE_MATCH_COUNT EQUAL 1)
        message(FATAL_ERROR "Could not extract major version number from utils/include/utils/version.hpp")
    endif()
    set(ver_major ${CMAKE_MATCH_1})

    string(REGEX MATCH "MIOS_VER_MINOR ([0-9]+)" _ "${file_contents}")
    if(NOT CMAKE_MATCH_COUNT EQUAL 1)
        message(FATAL_ERROR "Could not extract minor version number from utils/include/utils/version.hpp")
    endif()

    set(ver_minor ${CMAKE_MATCH_1})
    string(REGEX MATCH "MIOS_VER_PATCH ([0-9]+)" _ "${file_contents}")
    if(NOT CMAKE_MATCH_COUNT EQUAL 1)
        message(FATAL_ERROR "Could not extract patch version number from utils/include/utils/version.hpp")
    endif()
    set(ver_patch ${CMAKE_MATCH_1})

    set(MIOS_VERSION_MAJOR ${ver_major} PARENT_SCOPE)
    set(MIOS_VERSION_MINOR ${ver_minor} PARENT_SCOPE)
    set(MIOS_VERSION_PATCH ${ver_patch} PARENT_SCOPE)
    set(MIOS_VERSION "${ver_major}.${ver_minor}.${ver_patch}" PARENT_SCOPE)
endfunction()
